/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyBuilderRouteImport } from './routes/agency-builder'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as BusinessStrategyRouteImport } from './routes/business-strategy'
import { Route as SaasRouteImport } from './routes/saas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyBuilderRoute = AgencyBuilderRouteImport.update({
  id: '/agency-builder',
  path: '/agency-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessStrategyRoute = BusinessStrategyRouteImport.update({
  id: '/business-strategy',
  path: '/business-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency-builder': typeof AgencyBuilderRoute
  '/ai-automation': typeof AiAutomationRoute
  '/business-strategy': typeof BusinessStrategyRoute
  '/saas': typeof SaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency-builder': typeof AgencyBuilderRoute
  '/ai-automation': typeof AiAutomationRoute
  '/business-strategy': typeof BusinessStrategyRoute
  '/saas': typeof SaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency-builder': typeof AgencyBuilderRoute
  '/ai-automation': typeof AiAutomationRoute
  '/business-strategy': typeof BusinessStrategyRoute
  '/saas': typeof SaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/agency-builder' | '/ai-automation' | '/business-strategy' | '/saas'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/agency-builder' | '/ai-automation' | '/business-strategy' | '/saas'
  id:
    | '__root__'
    | '/'
    | '/agency-builder'
    | '/ai-automation'
    | '/business-strategy'
    | '/saas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyBuilderRoute: typeof AgencyBuilderRoute
  AiAutomationRoute: typeof AiAutomationRoute
  BusinessStrategyRoute: typeof BusinessStrategyRoute
  SaasRoute: typeof SaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-builder': {
      id: '/agency-builder'
      path: '/agency-builder'
      fullPath: '/agency-builder'
      preLoaderRoute: typeof AgencyBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-strategy': {
      id: '/business-strategy'
      path: '/business-strategy'
      fullPath: '/business-strategy'
      preLoaderRoute: typeof BusinessStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyBuilderRoute: AgencyBuilderRoute,
  AiAutomationRoute: AiAutomationRoute,
  BusinessStrategyRoute: BusinessStrategyRoute,
  SaasRoute: SaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
